[package]
name = "auto_heckin_texture_converter"
version = "5.0.2"
edition = "2021"

[dependencies]
ispc-texcomp = "0.1.18"
image = { git = "https://github.com/image-rs/image", rev = "b2018f8" }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.35.0", features = ["Win32_System_Console"] }

[features]
ispc = ["ispc-texcomp/ispc"]

[profile.release]
strip = true
codegen-units = 1
lto = true
