[package]
name = "auto_heckin_texture_converter"
version = "5.0.0"
edition = "2021"

[dependencies]
intel_tex = { git = "https://github.com/PowerBall253/intel-tex-rs", rev = "5f347dc" }
image = { git = "https://github.com/image-rs/image", rev = "53b9c5c" }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.33.0", features = ["Win32_System_Console"] }

[build-dependencies]
bindgen = "0.59.2"

[profile.release]
strip = true
codegen-units = 1
lto = true
