name: Build

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            filename: AutoHeckinTextureConverter-linux

          - os: macos-latest
            filename: AutoHeckinTextureConverter-osx

          - os: windows-latest
            filename: AutoHeckinTextureConverter-win64.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Backup oodle.h
        run: mv lib/oodle.h .

      - name: Clone lib repo
        uses: actions/checkout@v2
        with:
          repository: PowerBall253/lib
          token: ${{ secrets.ACCESS_TOKEN }}
          path: lib

      - name: Restore oodle.h
        run: mv oodle.h lib/

      - name: Switch to Rust nightly
        run: rustup default nightly

      - name: Build
        run: cargo build --release --verbose

      - name: Rename
        if: ${{ matrix.os == 'windows-latest' }}
        run: mv target/release/auto_heckin_texture_converter.exe ${{ matrix.filename }}

      - name: Rename
        if: ${{ matrix.os != 'windows-latest' }}
        run: mv target/release/auto_heckin_texture_converter ${{ matrix.filename }}

      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ github.workspace }}/${{ matrix.filename }}
          tag: ${{ github.ref }}
